# Site
name: "FDC3"
title: "FINOS FDC3 App Directory"
description: "Showcase for FINOS FDC3 Apps" 
logo: 'images/r1_logo_round_black.png'
favicon: favicon.ico
page_lang: en-GB
remote_theme: pages-themes/cayman@v0.2.0
plugins:
 - jekyll-remote-theme 
 - jekyll-redirect-from

baseurl: /v2

collections:
  apps:
    output: true
    permalink: /apps/:name/index.json
    
defaults:
  - scope:
      path: ""
      type: "apps"
    values:
      layout: "app-template"
